spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_network
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      format-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
file:
  upload-dir: ./uploads
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: Wdif6reUEVYXjIw8J9xGsIUBWy8tKXqaYYSQotiJfMo=
open:
  api:
    title: API document
    version: v1.0.0
    description: Mota Api service
    serverUrl: http://localhost:8089
    serverName: server test
server:
  port: 8089
